### ISSUE TITLE
Provide a Dockerfile with explicit version

### ISSUE THREAD

**Issue by louischan-oursky** [SkygearIO/py-skygear#3]
The ONBUILD Dockerfile depends on LATEST which in turn always install the master version. If I am using a specific skygear-server image, `docker-compose up` will definitely fail becuase the versions are not compatible.

The current workaround is to borrow some part of the Dockerfile but do not install the master version. Instead, specify the version of py-skygear in my requirements.txt

**Comment by cheungpat** [comment]
I think we have a lot of `Dockerfile` in the repo already and I was intended to remove some of the files. It is not that it is bad to provide the `Dockerfile` as you described, but IMHO a better solution should be to provide Docker image with specific versions.

It is not currently provided because making Docker Hub to build automatically with multiple `Dockerfile`s is problematic/difficult.

**Comment by cheungpat** [comment]
@louischan-oursky You can use this image to build from 0.6 version of py-skgyear: `quay.io/skygeario/py-skygear:v0.6.0-onbuild`. No login required.
